export type ObjectType = { name: string; passThrough: boolean; color: string };

export const ObjectTypes: Record<number, ObjectType> = {
  // Basic blocks
  0: { name: "Null", passThrough: true, color: "#000000" },
  1: { name: "Air", passThrough: true, color: "#87CEEB" },
  2: { name: "Water", passThrough: true, color: "#0077BE" },
  3: { name: "Bedrock", passThrough: false, color: "#2C2C2C" },
  4: { name: "Stone", passThrough: false, color: "#7D7D7D" },
  5: { name: "Deepslate", passThrough: false, color: "#4A4A4A" },
  6: { name: "Granite", passThrough: false, color: "#9B6B47" },
  7: { name: "Tuff", passThrough: false, color: "#6B5B4F" },
  8: { name: "Calcite", passThrough: false, color: "#E0E0E0" },
  9: { name: "Basalt", passThrough: false, color: "#3C3C3C" },
  10: { name: "SmoothBasalt", passThrough: false, color: "#333333" },
  11: { name: "Andesite", passThrough: false, color: "#8D8D8D" },
  12: { name: "Diorite", passThrough: false, color: "#C0C0C0" },
  13: { name: "Cobblestone", passThrough: false, color: "#808080" },
  14: { name: "MossyCobblestone", passThrough: false, color: "#6B8E5A" },
  15: { name: "Obsidian", passThrough: false, color: "#1C1C2E" },
  16: { name: "Dripstone", passThrough: false, color: "#8C7653" },
  17: { name: "Blackstone", passThrough: false, color: "#2B2B2B" },
  18: { name: "CobbledDeepslate", passThrough: false, color: "#5A5A5A" },
  19: { name: "Amethyst", passThrough: false, color: "#9966CC" },
  20: { name: "Glowstone", passThrough: false, color: "#FFCC66" },
  21: { name: "Grass", passThrough: false, color: "#7CB342" },
  22: { name: "Dirt", passThrough: false, color: "#8B5A2B" },
  23: { name: "Moss", passThrough: false, color: "#5A7C40" },
  24: { name: "Podzol", passThrough: false, color: "#6B4423" },
  25: { name: "DirtPath", passThrough: false, color: "#9B7653" },
  26: { name: "Mud", passThrough: false, color: "#6B4A2B" },
  27: { name: "PackedMud", passThrough: false, color: "#5A3A1B" },
  28: { name: "Farmland", passThrough: false, color: "#8B5533" },
  29: { name: "WetFarmland", passThrough: false, color: "#7B4A28" },
  30: { name: "UnrevealedOre", passThrough: false, color: "#404040" },
  31: { name: "Gravel", passThrough: false, color: "#808080" },
  32: { name: "Sand", passThrough: false, color: "#F2E6B6" },
  33: { name: "RedSand", passThrough: false, color: "#D4836A" },
  34: { name: "Sandstone", passThrough: false, color: "#F4DFC8" },
  35: { name: "RedSandstone", passThrough: false, color: "#D0906A" },
  36: { name: "Clay", passThrough: false, color: "#A0A0A0" },
  37: { name: "Terracotta", passThrough: false, color: "#9D5D33" },
  38: { name: "BrownTerracotta", passThrough: false, color: "#8B4513" },
  39: { name: "OrangeTerracotta", passThrough: false, color: "#FF6347" },
  40: { name: "WhiteTerracotta", passThrough: false, color: "#F5F5DC" },
  41: { name: "LightGrayTerracotta", passThrough: false, color: "#D3D3D3" },
  42: { name: "YellowTerracotta", passThrough: false, color: "#DAA520" },
  43: { name: "RedTerracotta", passThrough: false, color: "#CD5C5C" },
  44: { name: "LightBlueTerracotta", passThrough: false, color: "#87CEEB" },
  45: { name: "CyanTerracotta", passThrough: false, color: "#008B8B" },
  46: { name: "BlackTerracotta", passThrough: false, color: "#2F4F4F" },
  47: { name: "PurpleTerracotta", passThrough: false, color: "#9370DB" },
  48: { name: "BlueTerracotta", passThrough: false, color: "#4169E1" },
  49: { name: "MagentaTerracotta", passThrough: false, color: "#FF00FF" },

  // Wood blocks
  50: { name: "OakLog", passThrough: false, color: "#8B4513" },
  51: { name: "BirchLog", passThrough: false, color: "#F0E68C" },
  52: { name: "JungleLog", passThrough: false, color: "#8B5A2B" },
  53: { name: "SakuraLog", passThrough: false, color: "#DDA0DD" },
  54: { name: "AcaciaLog", passThrough: false, color: "#D2691E" },
  55: { name: "SpruceLog", passThrough: false, color: "#654321" },
  56: { name: "DarkOakLog", passThrough: false, color: "#3E2723" },
  57: { name: "MangroveLog", passThrough: false, color: "#8B4513" },
  58: { name: "OakLeaf", passThrough: false, color: "#228B22" },
  59: { name: "BirchLeaf", passThrough: false, color: "#7CFC00" },
  60: { name: "JungleLeaf", passThrough: false, color: "#006400" },
  61: { name: "SakuraLeaf", passThrough: false, color: "#FFB6C1" },
  62: { name: "SpruceLeaf", passThrough: false, color: "#2E8B57" },
  63: { name: "AcaciaLeaf", passThrough: false, color: "#32CD32" },
  64: { name: "DarkOakLeaf", passThrough: false, color: "#228B22" },
  65: { name: "AzaleaLeaf", passThrough: false, color: "#7B68EE" },
  66: { name: "FloweringAzaleaLeaf", passThrough: false, color: "#DA70D6" },
  67: { name: "MangroveLeaf", passThrough: false, color: "#556B2F" },
  68: { name: "MangroveRoots", passThrough: false, color: "#8B7355" },
  69: { name: "MuddyMangroveRoots", passThrough: false, color: "#6B5B47" },

  // Plants and flowers (passthrough)
  70: { name: "AzaleaFlower", passThrough: true, color: "#DDA0DD" },
  71: { name: "BellFlower", passThrough: true, color: "#6A5ACD" },
  72: { name: "DandelionFlower", passThrough: true, color: "#FFD700" },
  73: { name: "DaylilyFlower", passThrough: true, color: "#FF8C00" },
  74: { name: "LilacFlower", passThrough: true, color: "#DDA0DD" },
  75: { name: "RoseFlower", passThrough: true, color: "#DC143C" },
  76: { name: "FireFlower", passThrough: true, color: "#FF4500" },
  77: { name: "MorninggloryFlower", passThrough: true, color: "#9370DB" },
  78: { name: "PeonyFlower", passThrough: true, color: "#FFB6C1" },
  79: { name: "Ultraviolet", passThrough: true, color: "#8A2BE2" },
  80: { name: "SunFlower", passThrough: true, color: "#FFD700" },
  81: { name: "FlyTrap", passThrough: true, color: "#8FBC8F" },
  82: { name: "FescueGrass", passThrough: true, color: "#9ACD32" },
  83: { name: "SwitchGrass", passThrough: true, color: "#8FBC8F" },
  84: { name: "VinesBush", passThrough: true, color: "#228B22" },
  85: { name: "IvyVine", passThrough: true, color: "#006400" },
  86: { name: "HempBush", passThrough: true, color: "#6B8E23" },
  87: { name: "GoldenMushroom", passThrough: true, color: "#DAA520" },
  88: { name: "RedMushroom", passThrough: true, color: "#DC143C" },
  89: { name: "CoffeeBush", passThrough: true, color: "#8B4513" },
  90: { name: "StrawberryBush", passThrough: true, color: "#DC143C" },
  91: { name: "RaspberryBush", passThrough: true, color: "#DC143C" },
  92: { name: "Wheat", passThrough: true, color: "#DAA520" },
  93: { name: "CottonBush", passThrough: true, color: "#F5F5DC" },
  94: { name: "Pumpkin", passThrough: false, color: "#FF8C00" },
  95: { name: "Melon", passThrough: false, color: "#32CD32" },
  96: { name: "RedMushroomBlock", passThrough: false, color: "#DC143C" },
  97: { name: "BrownMushroomBlock", passThrough: false, color: "#8B4513" },
  98: { name: "MushroomStem", passThrough: false, color: "#F5F5DC" },
  99: { name: "BambooBush", passThrough: true, color: "#9ACD32" },
  100: { name: "Cactus", passThrough: false, color: "#228B22" },

  // Water blocks
  101: { name: "Coral", passThrough: true, color: "#FF7F50" },
  102: { name: "SeaAnemone", passThrough: true, color: "#FF6347" },
  103: { name: "Algae", passThrough: true, color: "#8FBC8F" },
  104: { name: "HornCoralBlock", passThrough: false, color: "#DAA520" },
  105: { name: "FireCoralBlock", passThrough: false, color: "#FF4500" },
  106: { name: "TubeCoralBlock", passThrough: false, color: "#4169E1" },
  107: { name: "BubbleCoralBlock", passThrough: false, color: "#FF69B4" },
  108: { name: "BrainCoralBlock", passThrough: false, color: "#FFB6C1" },

  // Environment
  109: { name: "Snow", passThrough: false, color: "#FFFAFA" },
  110: { name: "Ice", passThrough: false, color: "#B0E0E6" },
  111: { name: "Lava", passThrough: false, color: "#FF4500" },
  112: { name: "SpiderWeb", passThrough: false, color: "#F5F5DC" },
  113: { name: "Bone", passThrough: false, color: "#F5F5DC" },

  // Ores
  114: { name: "CoalOre", passThrough: false, color: "#2F4F4F" },
  115: { name: "CopperOre", passThrough: false, color: "#B87333" },
  116: { name: "IronOre", passThrough: false, color: "#CD853F" },
  117: { name: "GoldOre", passThrough: false, color: "#FFD700" },
  118: { name: "DiamondOre", passThrough: false, color: "#B9F2FF" },
  119: { name: "NeptuniumOre", passThrough: false, color: "#4169E1" },

  // Functional blocks
  120: { name: "TextSign", passThrough: false, color: "#8B4513" },
  121: { name: "OakPlanks", passThrough: false, color: "#DEB887" },
  122: { name: "BirchPlanks", passThrough: false, color: "#F5DEB3" },
  123: { name: "JunglePlanks", passThrough: false, color: "#D2B48C" },
  124: { name: "SakuraPlanks", passThrough: false, color: "#F0E68C" },
  125: { name: "SprucePlanks", passThrough: false, color: "#CD853F" },
  126: { name: "AcaciaPlanks", passThrough: false, color: "#DAA520" },
  127: { name: "DarkOakPlanks", passThrough: false, color: "#8B4513" },
  128: { name: "MangrovePlanks", passThrough: false, color: "#D2691E" },
  129: { name: "CopperBlock", passThrough: false, color: "#B87333" },
  130: { name: "IronBlock", passThrough: false, color: "#C0C0C0" },
  131: { name: "GoldBlock", passThrough: false, color: "#FFD700" },
  132: { name: "DiamondBlock", passThrough: false, color: "#B9F2FF" },
  133: { name: "NeptuniumBlock", passThrough: false, color: "#4169E1" },

  // Seeds and saplings (passthrough)
  134: { name: "WheatSeed", passThrough: true, color: "#DAA520" },
  135: { name: "PumpkinSeed", passThrough: true, color: "#FF8C00" },
  136: { name: "MelonSeed", passThrough: true, color: "#32CD32" },
  137: { name: "OakSapling", passThrough: true, color: "#228B22" },
  138: { name: "BirchSapling", passThrough: true, color: "#7CFC00" },
  139: { name: "JungleSapling", passThrough: true, color: "#006400" },
  140: { name: "SakuraSapling", passThrough: true, color: "#FFB6C1" },
  141: { name: "AcaciaSapling", passThrough: true, color: "#32CD32" },
  142: { name: "SpruceSapling", passThrough: true, color: "#2E8B57" },
  143: { name: "DarkOakSapling", passThrough: true, color: "#228B22" },
  144: { name: "MangroveSapling", passThrough: true, color: "#556B2F" },

  // Special blocks
  145: { name: "ForceField", passThrough: false, color: "#00FFFF" },
  146: { name: "Chest", passThrough: false, color: "#8B4513" },
  147: { name: "SpawnTile", passThrough: false, color: "#FFD700" },
  148: { name: "Bed", passThrough: false, color: "#DC143C" },
  149: { name: "Workbench", passThrough: false, color: "#8B4513" },
  150: { name: "Powerstone", passThrough: false, color: "#9370DB" },
  151: { name: "Furnace", passThrough: false, color: "#696969" },
  152: { name: "Torch", passThrough: true, color: "#FFD700" },

  // Tools and items (high IDs) - shouldn't appear in world but just in case
  32768: { name: "WoodenPick", passThrough: false, color: "#8B4513" },
  32769: { name: "CopperPick", passThrough: false, color: "#B87333" },
  32770: { name: "IronPick", passThrough: false, color: "#C0C0C0" },
  32771: { name: "GoldPick", passThrough: false, color: "#FFD700" },
  32772: { name: "DiamondPick", passThrough: false, color: "#B9F2FF" },
  32773: { name: "NeptuniumPick", passThrough: false, color: "#4169E1" },
  32774: { name: "WoodenAxe", passThrough: false, color: "#8B4513" },
  32775: { name: "CopperAxe", passThrough: false, color: "#B87333" },
  32776: { name: "IronAxe", passThrough: false, color: "#C0C0C0" },
  32777: { name: "GoldAxe", passThrough: false, color: "#FFD700" },
  32778: { name: "DiamondAxe", passThrough: false, color: "#B9F2FF" },
  32779: { name: "NeptuniumAxe", passThrough: false, color: "#4169E1" },
  32780: { name: "WoodenWhacker", passThrough: false, color: "#8B4513" },
  32781: { name: "CopperWhacker", passThrough: false, color: "#B87333" },
  32782: { name: "IronWhacker", passThrough: false, color: "#C0C0C0" },
  32783: { name: "WoodenHoe", passThrough: false, color: "#8B4513" },
  32784: { name: "GoldBar", passThrough: false, color: "#FFD700" },
  32785: { name: "IronBar", passThrough: false, color: "#C0C0C0" },
  32786: { name: "Diamond", passThrough: false, color: "#B9F2FF" },
  32787: { name: "NeptuniumBar", passThrough: false, color: "#4169E1" },
  32788: { name: "Bucket", passThrough: false, color: "#C0C0C0" },
  32789: { name: "WaterBucket", passThrough: false, color: "#0077BE" },
  32790: { name: "WheatSlop", passThrough: false, color: "#DAA520" },
  32791: { name: "PumpkinSoup", passThrough: false, color: "#FF8C00" },
  32792: { name: "MelonSmoothie", passThrough: false, color: "#32CD32" },
  32793: { name: "Battery", passThrough: false, color: "#FFD700" },
  32794: { name: "AnyLog", passThrough: false, color: "#8B4513" },
  32795: { name: "AnyPlank", passThrough: false, color: "#DEB887" },
  32796: { name: "AnyTerracotta", passThrough: false, color: "#9D5D33" },
  32797: { name: "AnyLeaf", passThrough: false, color: "#228B22" },
  32798: { name: "Player", passThrough: false, color: "#FFB6C1" },
  32799: { name: "Fragment", passThrough: false, color: "#B9F2FF" },
} as const;

// Helper function to find object ID by name
export function getObjectIdByName(name: string): number | undefined {
  const entry = Object.entries(ObjectTypes).find(
    ([_, obj]) => obj.name === name
  );
  return entry ? Number(entry[0]) : undefined;
}
